#!/usr/bin/env bash
# Generate a Natural program that seeds the CRUISE (41) and YACHT (42) Adabas
# files from CSV_Files/CRUISE.CSV.
#
# The repo's CSVs do NOT match the DDM field layouts (they carry a yacht NAME
# where CRUISE has a numeric ID-YACHT, a combined "YYYYMMDD-HH" date/time
# string where CRUISE has separate date and time fields, and a single price
# where CRUISE has three). The mapping applied here is therefore an explicit
# interpretation, not data shipped by the repo:
#   col1 -> CRUISE-ID
#   col2 -> yacht name, de-duplicated into YACHT; its row number becomes ID-YACHT
#   col3 -> START-DATE / START-TIME   (split on "-")
#   col4 -> END-DATE   / END-TIME     (split on "-")
#   col5 -> START-HARBOR
#   col6 -> DESTINATION-HARBOR
#   col7 -> PRICE-1W; PRICE-2W and PRICE-3W are derived as 2x and 3x
#   CRUISE-STATUS is set to '1' (available); YACHT-TYPE to 'Sailing Yacht'
set -euo pipefail

CSV="${CSV:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/CSV_Files/CRUISE.CSV}"
OUT=${1:-/tmp/SEEDCRU.NSP}

{
cat <<'HDR'
* Seeds CRUISE (file 41) and YACHT (file 42) from CRUISE.CSV.
* Generated by scripts/gen-seed.sh - not part of the upstream repo.
DEFINE DATA LOCAL
1 CV VIEW OF CRUISE
  2 CRUISE-ID (N8.0)
  2 CRUISE-STATUS (A1)
  2 START-DATE (N8.0)
  2 START-TIME (N6.0)
  2 END-DATE (N8.0)
  2 END-TIME (N6.0)
  2 START-HARBOR (A20)
  2 DESTINATION-HARBOR (A20)
  2 ID-YACHT (N8.0)
  2 PRICE-1W (P10.3)
  2 PRICE-2W (P10.3)
  2 PRICE-3W (P10.3)
1 YV VIEW OF YACHT
  2 YACHT-ID (N8.0)
  2 YACHT-NAME (A30)
  2 YACHT-TYPE (A30)
1 #N (I4)
END-DEFINE
HDR

# ---- YACHT rows: distinct names in first-seen order ----------------------
awk -F';' '
  { gsub(/"/,"",$2); gsub(/[ \t]+$/,"",$2)
    if (!($2 in seen)) { seen[$2]=++n; printf "%d\t%s\n", n, $2 } }
' "$CSV" | while IFS=$'\t' read -r id name; do
  printf "RESET YV\n"
  printf "YV.YACHT-ID := %s\n" "$id"
  printf "YV.YACHT-NAME := '%s'\n" "$name"
  printf "YV.YACHT-TYPE := 'Sailing Yacht'\n"
  printf "STORE YV\n"
done

# ---- CRUISE rows ---------------------------------------------------------
awk -F';' '
  { for (i=1;i<=NF;i++) { gsub(/"/,"",$i); gsub(/^[ \t]+|[ \t]+$/,"",$i) }
    if (!($2 in seen)) seen[$2]=++n
    split($3,s,"-"); split($4,e,"-")
    printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n", $1, seen[$2], s[1], s[2], e[1], e[2], $5, $6, $7 }
' "$CSV" | while IFS=$'\t' read -r cid yid sd st ed et sh dh price; do
  printf "RESET CV\n"
  printf "CV.CRUISE-ID := %s\n" "$cid"
  printf "CV.CRUISE-STATUS := '1'\n"
  printf "CV.START-DATE := %s\n" "$sd"
  printf "CV.START-TIME := %s\n" "${st:-0}"
  printf "CV.END-DATE := %s\n" "$ed"
  printf "CV.END-TIME := %s\n" "${et:-0}"
  printf "CV.START-HARBOR := '%s'\n" "$sh"
  printf "CV.DESTINATION-HARBOR := '%s'\n" "$dh"
  printf "CV.ID-YACHT := %s\n" "$yid"
  printf "CV.PRICE-1W := %s\n" "$price"
  printf "COMPUTE CV.PRICE-2W = %s * 2\n" "$price"
  printf "COMPUTE CV.PRICE-3W = %s * 3\n" "$price"
  printf "STORE CV\n"
done

cat <<'FTR'
END TRANSACTION
WRITE 'Seed complete.'
END
FTR
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"

# --- load it ---------------------------------------------------------------
# Stage, catalog and run the generated program inside the container. This needs
# the CRUISE and YACHT DDMs to already be cataloged, so run build-edu-lib.sh
# first - seeding is a post-build step, not a pre-build one.
command -v docker >/dev/null 2>&1 || export PATH="$HOME/.docker/bin:$PATH"
NAT="${NAT:-natural-ce}"
LIB="${LIB:-EDUPKG}"
NH=/opt/softwareag/Natural
FUSER="$NH/fuser/$LIB"

if ! docker exec "$NAT" test -f "$FUSER/GP/CRUISE.NGD"; then
  echo "error: CRUISE DDM is not cataloged in library $LIB." >&2
  echo "       run scripts/build-edu-lib.sh first, then re-run this script." >&2
  exit 1
fi

# Seeding is additive - STORE always inserts - so running this twice duplicates
# every record. Refuse if CRUISE already holds data unless FORCE=1 is set.
if [ "${FORCE:-0}" != "1" ]; then
  isn=$(docker exec "${ADA:-adabas-db}" sh -c \
    'cd /opt/softwareag/Adabas && ./adarep DBID=12 CONTENTS 2>&1 \
       | sed -n "/loaded on/,/^$/p" | awk "/ CRUISE /{print \$4}"' </dev/null \
    | tr -d ', ' || true)
  if [ -n "${isn:-}" ] && [ "${isn:-0}" -gt 0 ] 2>/dev/null; then
    echo "CRUISE already holds data (top ISN $isn); nothing to do."
    echo "To seed again anyway (this DUPLICATES records): FORCE=1 $0"
    exit 0
  fi
fi

docker cp "$OUT" "$NAT:$FUSER/SRC/SEEDCRU.NSP" >/dev/null
docker exec "$NAT" sh -c \
  "cd $FUSER && $NH/bin/ftouch lib=$LIB -s -a -f sm SEEDCRU.NSP" >/dev/null 2>&1

# Catalog and run as separate invocations: a NAT6805 editor work-file warning
# during READ/STOW aborts the rest of a combined command stack.
# Natural exits non-zero even on a successful STOW (it emits a NAT6805 editor
# work-file warning), so the exit status is ignored here; success is judged by
# the cataloged object existing.
docker exec "$NAT" sh -c \
  "cd $NH/bin && printf '\n\n\n\n' | ./natural BATCH SM=ON STACK=\"(LOGON $LIB;READ SEEDCRU;STOW;FIN)\"" \
  >/dev/null 2>&1 || true

if ! docker exec "$NAT" test -f "$FUSER/GP/SEEDCRU.NGP"; then
  echo "error: SEEDCRU failed to catalog" >&2; exit 1
fi

out=$(docker exec "$NAT" sh -c \
  "cd $NH/bin && printf '\n\n\n\n' | ./natural BATCH SM=ON ETID=SEED STACK=\"(LOGON $LIB;SEEDCRU;FIN)\"" 2>&1 \
  | tr -d '\033\016\017\r' || true)

if printf '%s' "$out" | grep -q 'Seed complete'; then
  echo "seed loaded"
  docker exec "${ADA:-adabas-db}" sh -c \
    'cd /opt/softwareag/Adabas && ./adarep DBID=12 CONTENTS 2>&1 | sed -n "/loaded on/,/^$/p" | grep -E "CRUISE|YACHT"' \
    </dev/null || true
else
  echo "error: seed program did not report completion:" >&2
  printf '%s\n' "$out" | grep -oE 'NAT[0-9]{4}[^|]{0,60}' | head -3 >&2
  exit 1
fi
